//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_view_date_pagos
    {
        public string nombre { get; set; }
        public Nullable<double> monto { get; set; }
        public System.DateTime fecha_nota { get; set; }
        public string Expr1 { get; set; }
        public string nota { get; set; }
    }
}
