//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_date_pagos
    {
        public int id_date_pagos { get; set; }
        public System.DateTime fecha_nota { get; set; }
        public string nota { get; set; }
        public int fk_id_pagos { get; set; }
        public int fk_id_status { get; set; }
        public Nullable<double> monto { get; set; }
    
        public virtual prc_pagos prc_pagos { get; set; }
        public virtual prc_status prc_status { get; set; }
    }
}
