//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_date_contratos
    {
        public int id_date_contratos { get; set; }
        public System.DateTime fecha_nota { get; set; }
        public string nota { get; set; }
        public int fk_id_contratos { get; set; }
    
        public virtual prc_contratos prc_contratos { get; set; }
    }
}
