//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_date_pagos
    {
        public int id_date_pagos { get; set; }
        public System.DateTime fecha_nota { get; set; }
        public string nota { get; set; }
        public int fk_id_pagos { get; set; }
        public int fk_id_status { get; set; }
    
        public virtual prc_pagos prc_pagos { get; set; }
        public virtual prc_status prc_status { get; set; }
    }
}
