//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_actividades
    {
        public prc_actividades()
        {
            this.prc_contratos = new HashSet<prc_contratos>();
            this.prc_pagos = new HashSet<prc_pagos>();
        }
    
        public int id_actividades { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<prc_contratos> prc_contratos { get; set; }
        public virtual ICollection<prc_pagos> prc_pagos { get; set; }
    }
}
