//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_recargos
    {
        public int id_recargos { get; set; }
        public int fk_id_date_pagos { get; set; }
        public string nota { get; set; }
        public double monto { get; set; }
        public string path_evidencia { get; set; }
    
        public virtual prc_date_pagos prc_date_pagos { get; set; }
    }
}
