//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_pagos
    {
        public prc_pagos()
        {
            this.prc_date_pagos = new HashSet<prc_date_pagos>();
        }
    
        public int id_pagos { get; set; }
        public System.DateTime date_inicio { get; set; }
        public System.DateTime date_final { get; set; }
        public int fk_id_conceptos { get; set; }
        public int fk_id_tipopagos { get; set; }
        public string fk_id_usuarios { get; set; }
        public Nullable<bool> activo { get; set; }
        public int fk_id_actividades { get; set; }
    
        public virtual prc_conceptos prc_conceptos { get; set; }
        public virtual ICollection<prc_date_pagos> prc_date_pagos { get; set; }
        public virtual prc_tipopagos prc_tipopagos { get; set; }
        public virtual prc_usuarios prc_usuarios { get; set; }
        public virtual prc_actividades prc_actividades { get; set; }
    }
}
