//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_actividades
    {
        public prc_actividades()
        {
            this.prc_contratos = new HashSet<prc_contratos>();
        }
    
        public int id_actividades { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<prc_contratos> prc_contratos { get; set; }
    }
}
