//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_contratos
    {
        public prc_contratos()
        {
            this.prc_date_contratos = new HashSet<prc_date_contratos>();
        }
    
        public int id_contratos { get; set; }
        public string concepto { get; set; }
        public int fk_id_actividades { get; set; }
        public string fk_id_usuarios { get; set; }
    
        public virtual prc_actividades prc_actividades { get; set; }
        public virtual prc_usuarios prc_usuarios { get; set; }
        public virtual ICollection<prc_date_contratos> prc_date_contratos { get; set; }
    }
}
