//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_status
    {
        public prc_status()
        {
            this.prc_date_pagos = new HashSet<prc_date_pagos>();
            this.prc_date_pagos_semanales = new HashSet<prc_date_pagos_semanales>();
        }
    
        public int id_status { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<prc_date_pagos> prc_date_pagos { get; set; }
        public virtual ICollection<prc_date_pagos_semanales> prc_date_pagos_semanales { get; set; }
    }
}
