//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_usuarios
    {
        public prc_usuarios()
        {
            this.prc_contratos = new HashSet<prc_contratos>();
            this.prc_pagos = new HashSet<prc_pagos>();
        }
    
        public string id_usuarios { get; set; }
        public string password { get; set; }
        public string nivel { get; set; }
        public string nombre { get; set; }
        public string puesto { get; set; }
    
        public virtual ICollection<prc_contratos> prc_contratos { get; set; }
        public virtual ICollection<prc_pagos> prc_pagos { get; set; }
    }
}
