//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_conceptos
    {
        public prc_conceptos()
        {
            this.prc_pagos = new HashSet<prc_pagos>();
        }
    
        public int id_conceptos { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<prc_pagos> prc_pagos { get; set; }
    }
}
