//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_status
    {
        public prc_status()
        {
            this.prc_date_pagos = new HashSet<prc_date_pagos>();
            this.prc_date_pagos_semanales = new HashSet<prc_date_pagos_semanales>();
        }
    
        public int id_status { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<prc_date_pagos> prc_date_pagos { get; set; }
        public virtual ICollection<prc_date_pagos_semanales> prc_date_pagos_semanales { get; set; }
    }
}
