//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagosRenovacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class prc_view_date_pagos
    {
        public string nombre { get; set; }
        public Nullable<double> monto { get; set; }
        public System.DateTime fecha_nota { get; set; }
        public string Expr1 { get; set; }
        public string nota { get; set; }
    }
}
