USE [master]
GO

/****** Object:  Database [dbpagoscontratos]    Script Date: 31/10/2014 13:20:46 ******/
CREATE DATABASE [dbpagoscontratos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbpagoscontratos', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\dbpagoscontratos.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbpagoscontratos_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\dbpagoscontratos_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbpagoscontratos] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbpagoscontratos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbpagoscontratos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbpagoscontratos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbpagoscontratos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbpagoscontratos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbpagoscontratos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbpagoscontratos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET RECOVERY FULL 
GO

ALTER DATABASE [dbpagoscontratos] SET  MULTI_USER 
GO

ALTER DATABASE [dbpagoscontratos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbpagoscontratos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbpagoscontratos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbpagoscontratos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbpagoscontratos] SET  READ_WRITE 
GO

