'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbpagoscontratosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbpagoscontratosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property prc_actividades() As DbSet(Of prc_actividades)
    Public Overridable Property prc_conceptos() As DbSet(Of prc_conceptos)
    Public Overridable Property prc_contratos() As DbSet(Of prc_contratos)
    Public Overridable Property prc_date_contratos() As DbSet(Of prc_date_contratos)
    Public Overridable Property prc_date_pagos() As DbSet(Of prc_date_pagos)
    Public Overridable Property prc_pagos() As DbSet(Of prc_pagos)
    Public Overridable Property prc_status() As DbSet(Of prc_status)
    Public Overridable Property prc_tipopagos() As DbSet(Of prc_tipopagos)
    Public Overridable Property prc_usuarios() As DbSet(Of prc_usuarios)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)

End Class
