'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class prc_contratos
    Public Property id_contratos As Integer
    Public Property concepto As String
    Public Property fk_id_actividades As Integer
    Public Property fk_id_usuarios As String

    Public Overridable Property prc_actividades As prc_actividades
    Public Overridable Property prc_usuarios As prc_usuarios
    Public Overridable Property prc_date_contratos As ICollection(Of prc_date_contratos) = New HashSet(Of prc_date_contratos)

End Class
