'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class prc_usuarios
    Public Property id_usuarios As String
    Public Property password As String
    Public Property nivel As String
    Public Property nombre As String
    Public Property puesto As String

    Public Overridable Property prc_contratos As ICollection(Of prc_contratos) = New HashSet(Of prc_contratos)
    Public Overridable Property prc_pagos As ICollection(Of prc_pagos) = New HashSet(Of prc_pagos)

End Class
