'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class prc_date_pagos
    Public Property id_date_pagos As Integer
    Public Property fecha_nota As Date
    Public Property nota As String
    Public Property fk_id_pagos As Integer

    Public Overridable Property prc_pagos As prc_pagos

End Class
