'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class prc_actividades
    Public Property id_actividades As Integer
    Public Property nombre As String

    Public Overridable Property prc_contratos As ICollection(Of prc_contratos) = New HashSet(Of prc_contratos)

End Class
