'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class prc_pagos
    Public Property id_pagos As Integer
    Public Property date_inicio As Date
    Public Property date_final As Date
    Public Property monto As Nullable(Of Double)
    Public Property fk_id_status As Integer
    Public Property fk_id_conceptos As Integer
    Public Property fk_id_tipopagos As Integer
    Public Property fk_id_usuarios As String

    Public Overridable Property prc_conceptos As prc_conceptos
    Public Overridable Property prc_date_pagos As ICollection(Of prc_date_pagos) = New HashSet(Of prc_date_pagos)
    Public Overridable Property prc_status As prc_status
    Public Overridable Property prc_tipopagos As prc_tipopagos
    Public Overridable Property prc_usuarios As prc_usuarios

End Class
